entero numero1,numero2
entero suma,resta,multi
inicio
escriba "escribe tus numeros"
llamar nueva_linea
lea numero1
lea numero2
llamar nueva_linea
escriba "el primer numero fue ",numero1," el segundo numero fue ",numero2
llamar nueva_linea
suma <- (numero1+numero2)
resta <- (numero1-numero2)
multi <- (numero1*numero2)
llamar nueva_linea
escriba "la sumas de estos dos numeros es ",suma," la resta es ",resta," y la multiplicacion es ",multi
fin