
real radio, perimetro, area, volumen 

inicio 

escriba "Ingrese el radio de la circunsferencia"
llamar nueva_linea
lea radio 
llamar nueva_linea 

perimetro <- 2*3.1416*radio
area <- 3.1416*(radio*radio)
volumen <- 4*3.1416*(radio*radio*radio)/3

escriba "El perimetro de la circunsferencia es ",perimetro
llamar nueva_linea

escriba "El area area del circulo es de ", area
llamar nueva_linea

escriba "El volumen de la esfera es de ", volumen 

fin